package vn.com.vti.bus.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import vn.com.vti.bus.entity.Bus;
import vn.com.vti.bus.entity.BusExample;

public interface BusMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.bus
     *
     * @mbg.generated Fri Oct 28 23:04:58 JST 2022
     */
    long countByExample(BusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.bus
     *
     * @mbg.generated Fri Oct 28 23:04:58 JST 2022
     */
    int deleteByExample(BusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.bus
     *
     * @mbg.generated Fri Oct 28 23:04:58 JST 2022
     */
    int deleteByPrimaryKey(Integer busId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.bus
     *
     * @mbg.generated Fri Oct 28 23:04:58 JST 2022
     */
    int insert(Bus row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.bus
     *
     * @mbg.generated Fri Oct 28 23:04:58 JST 2022
     */
    int insertSelective(Bus row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.bus
     *
     * @mbg.generated Fri Oct 28 23:04:58 JST 2022
     */
    List<Bus> selectByExample(BusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.bus
     *
     * @mbg.generated Fri Oct 28 23:04:58 JST 2022
     */
    Bus selectByPrimaryKey(Integer busId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.bus
     *
     * @mbg.generated Fri Oct 28 23:04:58 JST 2022
     */
    int updateByExampleSelective(@Param("row") Bus row, @Param("example") BusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.bus
     *
     * @mbg.generated Fri Oct 28 23:04:58 JST 2022
     */
    int updateByExample(@Param("row") Bus row, @Param("example") BusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.bus
     *
     * @mbg.generated Fri Oct 28 23:04:58 JST 2022
     */
    int updateByPrimaryKeySelective(Bus row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.bus
     *
     * @mbg.generated Fri Oct 28 23:04:58 JST 2022
     */
    int updateByPrimaryKey(Bus row);
}