package vn.com.vti.bus.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import vn.com.vti.bus.entity.Bus;
import vn.com.vti.bus.entity.BusExample;

public interface BusMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.bus
     *
     * @mbg.generated Tue Jun 02 05:35:19 JST 2020
     */
    long countByExample(BusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.bus
     *
     * @mbg.generated Tue Jun 02 05:35:19 JST 2020
     */
    int deleteByExample(BusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.bus
     *
     * @mbg.generated Tue Jun 02 05:35:19 JST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.bus
     *
     * @mbg.generated Tue Jun 02 05:35:19 JST 2020
     */
    int insert(Bus record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.bus
     *
     * @mbg.generated Tue Jun 02 05:35:19 JST 2020
     */
    int insertSelective(Bus record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.bus
     *
     * @mbg.generated Tue Jun 02 05:35:19 JST 2020
     */
    List<Bus> selectByExample(BusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.bus
     *
     * @mbg.generated Tue Jun 02 05:35:19 JST 2020
     */
    Bus selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.bus
     *
     * @mbg.generated Tue Jun 02 05:35:19 JST 2020
     */
    int updateByExampleSelective(@Param("record") Bus record, @Param("example") BusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.bus
     *
     * @mbg.generated Tue Jun 02 05:35:19 JST 2020
     */
    int updateByExample(@Param("record") Bus record, @Param("example") BusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.bus
     *
     * @mbg.generated Tue Jun 02 05:35:19 JST 2020
     */
    int updateByPrimaryKeySelective(Bus record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.bus
     *
     * @mbg.generated Tue Jun 02 05:35:19 JST 2020
     */
    int updateByPrimaryKey(Bus record);
}