package vn.com.vti.bus.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import vn.com.vti.bus.entity.BusStation;
import vn.com.vti.bus.entity.BusStationExample;

public interface BusStationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.bus_station
     *
     * @mbg.generated Fri Oct 28 23:10:12 JST 2022
     */
    long countByExample(BusStationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.bus_station
     *
     * @mbg.generated Fri Oct 28 23:10:12 JST 2022
     */
    int deleteByExample(BusStationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.bus_station
     *
     * @mbg.generated Fri Oct 28 23:10:12 JST 2022
     */
    int deleteByPrimaryKey(Integer busStationId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.bus_station
     *
     * @mbg.generated Fri Oct 28 23:10:12 JST 2022
     */
    int insert(BusStation row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.bus_station
     *
     * @mbg.generated Fri Oct 28 23:10:12 JST 2022
     */
    int insertSelective(BusStation row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.bus_station
     *
     * @mbg.generated Fri Oct 28 23:10:12 JST 2022
     */
    List<BusStation> selectByExample(BusStationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.bus_station
     *
     * @mbg.generated Fri Oct 28 23:10:12 JST 2022
     */
    BusStation selectByPrimaryKey(Integer busStationId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.bus_station
     *
     * @mbg.generated Fri Oct 28 23:10:12 JST 2022
     */
    int updateByExampleSelective(@Param("row") BusStation row, @Param("example") BusStationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.bus_station
     *
     * @mbg.generated Fri Oct 28 23:10:12 JST 2022
     */
    int updateByExample(@Param("row") BusStation row, @Param("example") BusStationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.bus_station
     *
     * @mbg.generated Fri Oct 28 23:10:12 JST 2022
     */
    int updateByPrimaryKeySelective(BusStation row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.bus_station
     *
     * @mbg.generated Fri Oct 28 23:10:12 JST 2022
     */
    int updateByPrimaryKey(BusStation row);
}