package vn.com.vti.bus.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import vn.com.vti.bus.entity.Member;
import vn.com.vti.bus.entity.MemberExample;

public interface MemberMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.member
     *
     * @mbg.generated Fri Oct 28 23:10:12 JST 2022
     */
    long countByExample(MemberExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.member
     *
     * @mbg.generated Fri Oct 28 23:10:12 JST 2022
     */
    int deleteByExample(MemberExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.member
     *
     * @mbg.generated Fri Oct 28 23:10:12 JST 2022
     */
    int deleteByPrimaryKey(Integer memberId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.member
     *
     * @mbg.generated Fri Oct 28 23:10:12 JST 2022
     */
    int insert(Member row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.member
     *
     * @mbg.generated Fri Oct 28 23:10:12 JST 2022
     */
    int insertSelective(Member row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.member
     *
     * @mbg.generated Fri Oct 28 23:10:12 JST 2022
     */
    List<Member> selectByExample(MemberExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.member
     *
     * @mbg.generated Fri Oct 28 23:10:12 JST 2022
     */
    Member selectByPrimaryKey(Integer memberId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.member
     *
     * @mbg.generated Fri Oct 28 23:10:12 JST 2022
     */
    int updateByExampleSelective(@Param("row") Member row, @Param("example") MemberExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.member
     *
     * @mbg.generated Fri Oct 28 23:10:12 JST 2022
     */
    int updateByExample(@Param("row") Member row, @Param("example") MemberExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.member
     *
     * @mbg.generated Fri Oct 28 23:10:12 JST 2022
     */
    int updateByPrimaryKeySelective(Member row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.member
     *
     * @mbg.generated Fri Oct 28 23:10:12 JST 2022
     */
    int updateByPrimaryKey(Member row);
}