package vn.com.vti.bus.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import vn.com.vti.bus.entity.OperationManager;
import vn.com.vti.bus.entity.OperationManagerExample;

public interface OperationManagerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.operation_manager
     *
     * @mbg.generated Fri Oct 28 23:10:12 JST 2022
     */
    long countByExample(OperationManagerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.operation_manager
     *
     * @mbg.generated Fri Oct 28 23:10:12 JST 2022
     */
    int deleteByExample(OperationManagerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.operation_manager
     *
     * @mbg.generated Fri Oct 28 23:10:12 JST 2022
     */
    int deleteByPrimaryKey(Integer adminstratorId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.operation_manager
     *
     * @mbg.generated Fri Oct 28 23:10:12 JST 2022
     */
    int insert(OperationManager row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.operation_manager
     *
     * @mbg.generated Fri Oct 28 23:10:12 JST 2022
     */
    int insertSelective(OperationManager row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.operation_manager
     *
     * @mbg.generated Fri Oct 28 23:10:12 JST 2022
     */
    List<OperationManager> selectByExample(OperationManagerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.operation_manager
     *
     * @mbg.generated Fri Oct 28 23:10:12 JST 2022
     */
    OperationManager selectByPrimaryKey(Integer adminstratorId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.operation_manager
     *
     * @mbg.generated Fri Oct 28 23:10:12 JST 2022
     */
    int updateByExampleSelective(@Param("row") OperationManager row, @Param("example") OperationManagerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.operation_manager
     *
     * @mbg.generated Fri Oct 28 23:10:12 JST 2022
     */
    int updateByExample(@Param("row") OperationManager row, @Param("example") OperationManagerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.operation_manager
     *
     * @mbg.generated Fri Oct 28 23:10:12 JST 2022
     */
    int updateByPrimaryKeySelective(OperationManager row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.operation_manager
     *
     * @mbg.generated Fri Oct 28 23:10:12 JST 2022
     */
    int updateByPrimaryKey(OperationManager row);
}