package vn.com.vti.bus.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import vn.com.vti.bus.entity.Reserve;
import vn.com.vti.bus.entity.ReserveExample;

public interface ReserveMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.reserve
     *
     * @mbg.generated Fri Oct 28 23:10:12 JST 2022
     */
    long countByExample(ReserveExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.reserve
     *
     * @mbg.generated Fri Oct 28 23:10:12 JST 2022
     */
    int deleteByExample(ReserveExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.reserve
     *
     * @mbg.generated Fri Oct 28 23:10:12 JST 2022
     */
    int deleteByPrimaryKey(Integer reserveId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.reserve
     *
     * @mbg.generated Fri Oct 28 23:10:12 JST 2022
     */
    int insert(Reserve row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.reserve
     *
     * @mbg.generated Fri Oct 28 23:10:12 JST 2022
     */
    int insertSelective(Reserve row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.reserve
     *
     * @mbg.generated Fri Oct 28 23:10:12 JST 2022
     */
    List<Reserve> selectByExample(ReserveExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.reserve
     *
     * @mbg.generated Fri Oct 28 23:10:12 JST 2022
     */
    Reserve selectByPrimaryKey(Integer reserveId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.reserve
     *
     * @mbg.generated Fri Oct 28 23:10:12 JST 2022
     */
    int updateByExampleSelective(@Param("row") Reserve row, @Param("example") ReserveExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.reserve
     *
     * @mbg.generated Fri Oct 28 23:10:12 JST 2022
     */
    int updateByExample(@Param("row") Reserve row, @Param("example") ReserveExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.reserve
     *
     * @mbg.generated Fri Oct 28 23:10:12 JST 2022
     */
    int updateByPrimaryKeySelective(Reserve row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.reserve
     *
     * @mbg.generated Fri Oct 28 23:10:12 JST 2022
     */
    int updateByPrimaryKey(Reserve row);
}