package vn.com.vti.bus.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import vn.com.vti.bus.entity.Seat;
import vn.com.vti.bus.entity.SeatExample;

public interface SeatMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.seat
     *
     * @mbg.generated Fri Oct 28 23:10:12 JST 2022
     */
    long countByExample(SeatExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.seat
     *
     * @mbg.generated Fri Oct 28 23:10:12 JST 2022
     */
    int deleteByExample(SeatExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.seat
     *
     * @mbg.generated Fri Oct 28 23:10:12 JST 2022
     */
    int deleteByPrimaryKey(Integer seatId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.seat
     *
     * @mbg.generated Fri Oct 28 23:10:12 JST 2022
     */
    int insert(Seat row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.seat
     *
     * @mbg.generated Fri Oct 28 23:10:12 JST 2022
     */
    int insertSelective(Seat row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.seat
     *
     * @mbg.generated Fri Oct 28 23:10:12 JST 2022
     */
    List<Seat> selectByExample(SeatExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.seat
     *
     * @mbg.generated Fri Oct 28 23:10:12 JST 2022
     */
    Seat selectByPrimaryKey(Integer seatId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.seat
     *
     * @mbg.generated Fri Oct 28 23:10:12 JST 2022
     */
    int updateByExampleSelective(@Param("row") Seat row, @Param("example") SeatExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.seat
     *
     * @mbg.generated Fri Oct 28 23:10:12 JST 2022
     */
    int updateByExample(@Param("row") Seat row, @Param("example") SeatExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.seat
     *
     * @mbg.generated Fri Oct 28 23:10:12 JST 2022
     */
    int updateByPrimaryKeySelective(Seat row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.seat
     *
     * @mbg.generated Fri Oct 28 23:10:12 JST 2022
     */
    int updateByPrimaryKey(Seat row);
}