-- BUS_STATION TABLE'S SAMPLES DATA
INSERT INTO BUS_STATION(PREFECTURE, BUS_STATION_NAME) VALUES
('東京都','東京駅〔八重洲南口〕');
INSERT INTO BUS_STATION(PREFECTURE, BUS_STATION_NAME) VALUES
('東京都','東京駅〔日本橋口〕');
INSERT INTO BUS_STATION(PREFECTURE, BUS_STATION_NAME) VALUES
('東京都','東京駅八重洲口前');
INSERT INTO BUS_STATION(PREFECTURE, BUS_STATION_NAME) VALUES
('東京都','赤羽駅東口');
INSERT INTO BUS_STATION(PREFECTURE, BUS_STATION_NAME) VALUES
('東京都','秋葉原駅前');
INSERT INTO BUS_STATION(PREFECTURE, BUS_STATION_NAME) VALUES
('東京都','浅草雷門');
INSERT INTO BUS_STATION(PREFECTURE, BUS_STATION_NAME) VALUES
('東京都','池袋駅東口');
INSERT INTO BUS_STATION(PREFECTURE, BUS_STATION_NAME) VALUES
('東京都','上野駅前');
INSERT INTO BUS_STATION(PREFECTURE, BUS_STATION_NAME) VALUES
('東京都','有明ガーデン');
INSERT INTO BUS_STATION(PREFECTURE, BUS_STATION_NAME) VALUES
('東京都','新宿駅西口');
INSERT INTO BUS_STATION(PREFECTURE, BUS_STATION_NAME) VALUES
('東京都','田町駅東口');
INSERT INTO BUS_STATION(PREFECTURE, BUS_STATION_NAME) VALUES
('東京都','東京駅丸の内北口');
INSERT INTO BUS_STATION(PREFECTURE, BUS_STATION_NAME) VALUES
('東京都','東京タワー〔構内〕');
INSERT INTO BUS_STATION(PREFECTURE, BUS_STATION_NAME) VALUES
('東京都','国際展示場駅前');
INSERT INTO BUS_STATION(PREFECTURE, BUS_STATION_NAME) VALUES
('東京都','渋谷マークシティ');
INSERT INTO BUS_STATION(PREFECTURE, BUS_STATION_NAME) VALUES
('東京都','二子玉川ライズ・楽天クリムゾンハウス');
INSERT INTO BUS_STATION(PREFECTURE, BUS_STATION_NAME) VALUES
('東京都','京王八王子駅');
INSERT INTO BUS_STATION(PREFECTURE, BUS_STATION_NAME) VALUES
('東京都','高尾駅南口');
INSERT INTO BUS_STATION(PREFECTURE, BUS_STATION_NAME) VALUES
('東京都','聖蹟桜ヶ丘駅');
INSERT INTO BUS_STATION(PREFECTURE, BUS_STATION_NAME) VALUES
('東京都','中野駅(東京都)');
INSERT INTO BUS_STATION(PREFECTURE, BUS_STATION_NAME) VALUES
('千葉県','成田空港第２ターミナル');
INSERT INTO BUS_STATION(PREFECTURE, BUS_STATION_NAME) VALUES
('千葉県','成田空港第１ターミナル');
INSERT INTO BUS_STATION(PREFECTURE, BUS_STATION_NAME) VALUES
('千葉県','成田空港第３ターミナル');
INSERT INTO BUS_STATION(PREFECTURE, BUS_STATION_NAME) VALUES
('千葉県','東京ディズニーシー');
INSERT INTO BUS_STATION(PREFECTURE, BUS_STATION_NAME) VALUES
('千葉県','東京ディズニーランド');
INSERT INTO BUS_STATION(PREFECTURE, BUS_STATION_NAME) VALUES
('千葉県','西船橋駅〔高速バス〕');
INSERT INTO BUS_STATION(PREFECTURE, BUS_STATION_NAME) VALUES
('千葉県','津田沼駅');
INSERT INTO BUS_STATION(PREFECTURE, BUS_STATION_NAME) VALUES
('千葉県','第三中学校(千葉県)');
INSERT INTO BUS_STATION(PREFECTURE, BUS_STATION_NAME) VALUES
('千葉県','京成津田沼駅');
INSERT INTO BUS_STATION(PREFECTURE, BUS_STATION_NAME) VALUES
('千葉県','海浜幕張駅');
INSERT INTO BUS_STATION(PREFECTURE, BUS_STATION_NAME) VALUES
('千葉県','幕張メッセ中央');
INSERT INTO BUS_STATION(PREFECTURE, BUS_STATION_NAME) VALUES
('千葉県','小倉団地入口');
INSERT INTO BUS_STATION(PREFECTURE, BUS_STATION_NAME) VALUES
('千葉県','小倉台駅');
INSERT INTO BUS_STATION(PREFECTURE, BUS_STATION_NAME) VALUES
('千葉県','小倉団地(千葉県)');
INSERT INTO BUS_STATION(PREFECTURE, BUS_STATION_NAME) VALUES
('千葉県','千城台北駅');
INSERT INTO BUS_STATION(PREFECTURE, BUS_STATION_NAME) VALUES
('千葉県','千城台駅');
INSERT INTO BUS_STATION(PREFECTURE, BUS_STATION_NAME) VALUES
('千葉県','御成台入口');
INSERT INTO BUS_STATION(PREFECTURE, BUS_STATION_NAME) VALUES
('千葉県','清爽の街');
INSERT INTO BUS_STATION(PREFECTURE, BUS_STATION_NAME) VALUES
('千葉県','御成台中央');
INSERT INTO BUS_STATION(PREFECTURE, BUS_STATION_NAME) VALUES
('千葉県','情報大学正門');
INSERT INTO BUS_STATION(PREFECTURE, BUS_STATION_NAME) VALUES
('大坂府','ＵＳＪ');
INSERT INTO BUS_STATION(PREFECTURE, BUS_STATION_NAME) VALUES
('大坂府','千里ニュータウン');
INSERT INTO BUS_STATION(PREFECTURE, BUS_STATION_NAME) VALUES
('大坂府','大阪梅田〔阪急三番街〕');
INSERT INTO BUS_STATION(PREFECTURE, BUS_STATION_NAME) VALUES
('大坂府','天王寺駅前');
INSERT INTO BUS_STATION(PREFECTURE, BUS_STATION_NAME) VALUES
('大坂府','湊町バスターミナル〔ＯＣＡＴ〕');
INSERT INTO BUS_STATION(PREFECTURE, BUS_STATION_NAME) VALUES
('大坂府','名神茨木');
INSERT INTO BUS_STATION(PREFECTURE, BUS_STATION_NAME) VALUES
('大坂府','名神高槻');
INSERT INTO BUS_STATION(PREFECTURE, BUS_STATION_NAME) VALUES
('大坂府','堺東駅前');
INSERT INTO BUS_STATION(PREFECTURE, BUS_STATION_NAME) VALUES
('大坂府','少路駅');
INSERT INTO BUS_STATION(PREFECTURE, BUS_STATION_NAME) VALUES
('大坂府','新大阪〔阪急バスターミナル〕');
INSERT INTO BUS_STATION(PREFECTURE, BUS_STATION_NAME) VALUES
('大坂府','和泉中央駅');
INSERT INTO BUS_STATION(PREFECTURE, BUS_STATION_NAME) VALUES
('大坂府','大阪駅ＪＲ高速バスターミナル');
INSERT INTO BUS_STATION(PREFECTURE, BUS_STATION_NAME) VALUES
('大坂府','りんくうタウン駅');
INSERT INTO BUS_STATION(PREFECTURE, BUS_STATION_NAME) VALUES
('大坂府','阪急茨木市駅');
INSERT INTO BUS_STATION(PREFECTURE, BUS_STATION_NAME) VALUES
('大坂府','大阪駅前〔東梅田駅〕');
INSERT INTO BUS_STATION(PREFECTURE, BUS_STATION_NAME) VALUES
('大坂府','あべのハルカス／天王寺駅〔高速バス〕');
INSERT INTO BUS_STATION(PREFECTURE, BUS_STATION_NAME) VALUES
('大坂府','樟葉駅');
INSERT INTO BUS_STATION(PREFECTURE, BUS_STATION_NAME) VALUES
('大坂府','枚方市駅北口');
INSERT INTO BUS_STATION(PREFECTURE, BUS_STATION_NAME) VALUES
('大坂府','ＪＲ茨木');
INSERT INTO BUS_STATION(PREFECTURE, BUS_STATION_NAME) VALUES
('大坂府','ＪＲ堺市駅前');
INSERT INTO BUS_STATION(PREFECTURE, BUS_STATION_NAME) VALUES
('茨城県','つくばセンター');
INSERT INTO BUS_STATION(PREFECTURE, BUS_STATION_NAME) VALUES
('茨城県','赤塚駅北口');
INSERT INTO BUS_STATION(PREFECTURE, BUS_STATION_NAME) VALUES
('茨城県','石岡〔高速バス〕');
INSERT INTO BUS_STATION(PREFECTURE, BUS_STATION_NAME) VALUES
('茨城県','石川三丁目');
INSERT INTO BUS_STATION(PREFECTURE, BUS_STATION_NAME) VALUES
('茨城県','泉入口(常陸大宮市)');
INSERT INTO BUS_STATION(PREFECTURE, BUS_STATION_NAME) VALUES
('茨城県','泉町一丁目(茨城県)');
INSERT INTO BUS_STATION(PREFECTURE, BUS_STATION_NAME) VALUES
('茨城県','茨城交通大子営業所');
INSERT INTO BUS_STATION(PREFECTURE, BUS_STATION_NAME) VALUES
('茨城県','大塚(水戸市)');
INSERT INTO BUS_STATION(PREFECTURE, BUS_STATION_NAME) VALUES
('茨城県','大塚東');
INSERT INTO BUS_STATION(PREFECTURE, BUS_STATION_NAME) VALUES
('茨城県','鹿島宇宙センター');
INSERT INTO BUS_STATION(PREFECTURE, BUS_STATION_NAME) VALUES
('茨城県','鹿嶋市役所');
INSERT INTO BUS_STATION(PREFECTURE, BUS_STATION_NAME) VALUES
('茨城県','鹿島神宮駅');
INSERT INTO BUS_STATION(PREFECTURE, BUS_STATION_NAME) VALUES
('茨城県','鹿島セントラルホテル');
INSERT INTO BUS_STATION(PREFECTURE, BUS_STATION_NAME) VALUES
('茨城県','県自動車学校');
INSERT INTO BUS_STATION(PREFECTURE, BUS_STATION_NAME) VALUES
('茨城県','常陸太田市高速バスターミナル');
INSERT INTO BUS_STATION(PREFECTURE, BUS_STATION_NAME) VALUES
('茨城県','鴻巣');
INSERT INTO BUS_STATION(PREFECTURE, BUS_STATION_NAME) VALUES
('茨城県','下広岡');
INSERT INTO BUS_STATION(PREFECTURE, BUS_STATION_NAME) VALUES
('茨城県','自由ケ丘(茨城県)');
INSERT INTO BUS_STATION(PREFECTURE, BUS_STATION_NAME) VALUES
('茨城県','新田中内');
INSERT INTO BUS_STATION(PREFECTURE, BUS_STATION_NAME) VALUES
('茨城県','新原三差路');
INSERT INTO BUS_STATION(PREFECTURE, BUS_STATION_NAME) VALUES
('群馬県','伊香保温泉〔見晴下〕');
INSERT INTO BUS_STATION(PREFECTURE, BUS_STATION_NAME) VALUES
('群馬県','草津温泉バスターミナル');
INSERT INTO BUS_STATION(PREFECTURE, BUS_STATION_NAME) VALUES
('群馬県','渋川駅前');
INSERT INTO BUS_STATION(PREFECTURE, BUS_STATION_NAME) VALUES
('群馬県','伊勢崎駅');
INSERT INTO BUS_STATION(PREFECTURE, BUS_STATION_NAME) VALUES
('群馬県','伊香保石段街');
INSERT INTO BUS_STATION(PREFECTURE, BUS_STATION_NAME) VALUES
('群馬県','桐生駅南口');
INSERT INTO BUS_STATION(PREFECTURE, BUS_STATION_NAME) VALUES
('群馬県','太田駅南口');
INSERT INTO BUS_STATION(PREFECTURE, BUS_STATION_NAME) VALUES
('群馬県','ＢＵＳターミナルおおた');
INSERT INTO BUS_STATION(PREFECTURE, BUS_STATION_NAME) VALUES
('群馬県','大泉町役場');
INSERT INTO BUS_STATION(PREFECTURE, BUS_STATION_NAME) VALUES
('群馬県','館林市役所');
INSERT INTO BUS_STATION(PREFECTURE, BUS_STATION_NAME) VALUES
('群馬県','前橋バスセンター');
INSERT INTO BUS_STATION(PREFECTURE, BUS_STATION_NAME) VALUES
('群馬県','前橋駅南口');
INSERT INTO BUS_STATION(PREFECTURE, BUS_STATION_NAME) VALUES
('群馬県','ｎパーキング日高');
INSERT INTO BUS_STATION(PREFECTURE, BUS_STATION_NAME) VALUES
('群馬県','高崎バスセンター');
INSERT INTO BUS_STATION(PREFECTURE, BUS_STATION_NAME) VALUES
('群馬県','高崎駅東口');
INSERT INTO BUS_STATION(PREFECTURE, BUS_STATION_NAME) VALUES
('群馬県','藤岡インター');
INSERT INTO BUS_STATION(PREFECTURE, BUS_STATION_NAME) VALUES
('群馬県','邑楽町役場');
INSERT INTO BUS_STATION(PREFECTURE, BUS_STATION_NAME) VALUES
('群馬県','安中市役所');
INSERT INTO BUS_STATION(PREFECTURE, BUS_STATION_NAME) VALUES
('群馬県','温泉口〔中之条町四万〕');
INSERT INTO BUS_STATION(PREFECTURE, BUS_STATION_NAME) VALUES
('群馬県','下仁田');