-- JOIN ROUTE TABLE AND BUS_STATION TABLE TO EXPORT BUS_STATION_NAME ONLY
SELECT DISTINCT
	T.DEPARTURE_ID
	,T.DEPARTURE_STATION_NAME
	,T.ARRIVAL_ID
	,BS1.BUS_STATION_NAME AS ARRIVAL_STATION_NAME
FROM (
	SELECT
		R.*
		,BS.BUS_STATION_NAME AS DEPARTURE_STATION_NAME
	FROM 
		BUS_STATION AS BS
		INNER JOIN ROUTE AS R
			ON BS.BUS_STATION_ID = R.DEPARTURE_ID)
	T
		INNER JOIN BUS_STATION AS BS1
		ON BS1.BUS_STATION_ID = T.ARRIVAL_ID;
		
		
-- JOIN ROUTE TABLE AND BUS_STATION TABLE TO EXPORT BUS_STATION_NAME AND ANOTHER INFORMATION
		
SELECT
	T.*
	,BS1.BUS_STATION_NAME AS ARRIVAL_STATION_NAME
FROM (
	SELECT
		R.*
		,BS.BUS_STATION_NAME AS DEPARTURE_STATION_NAME
	FROM 
		BUS_STATION AS BS
		INNER JOIN ROUTE AS R
			ON BS.BUS_STATION_ID = R.DEPARTURE_ID)
	T
		INNER JOIN BUS_STATION AS BS1
		ON BS1.BUS_STATION_ID = T.ARRIVAL_ID
WHERE
	T.ROUTE_ID = #{routeId};
	
-- JOIN MEMBER TABLE AND RESERVER TABLE AND ROUTE TABLE TO EXTRACT MEMBER RESERVATION INFORMATION BY MEMBER ID
SELECT 
	R.RESERVED_DATE
	,R.ROUTE_ID
	,RO.DEPARTURE_ID
	,RO.ARRIVAL_ID
	,RO.PRICE
	,RO.BUS_ID
	,M.MEMBER_ID
FROM 
	RESERVE AS R
	INNER JOIN MEMBER AS M
		ON R.MEMBER_ID = M.MEMBER_ID
	INNER JOIN ROUTE AS RO
		ON R.ROUTE_ID = RO.ROUTE_ID	
WHERE 
	M.MEMBER_ID = 2;
	

--FIND OUT THE UNBOOKING SEAT
SELECT 
	S.BUS_ID
	,S.SEAT_NUMBER
	,S.RESERVE_ID
	,R.ROUTE_ID
	,R.DEPARTURE_DATE
	,RO.DEPARTURE_ID
	,RO.ARRIVAL_ID
	,RO.PRICE
FROM 
	SEAT AS S
	INNER JOIN BUS AS B
		ON S.BUS_ID = B.BUS_ID
	INNER JOIN RESERVE AS R
		ON S.RESERVE_ID = R.RESERVE_ID
	INNER JOIN ROUTE AS RO
		ON R.ROUTE_ID = RO.ROUTE_ID
GROUP BY 
	S.BUS_ID
	,S.SEAT_NUMBER
	,S.RESERVE_ID
	,R.ROUTE_ID
	,R.DEPARTURE_DATE
	,RO.DEPARTURE_ID
	,RO.ARRIVAL_ID
	,RO.PRICE
HAVING 
	R.DEPARTURE_DATE = '2015-01-12'
	AND RO.DEPARTURE_ID = 1
	AND RO.ARRIVAL_ID = 2
ORDER BY 
	S.BUS_ID;