-- JOIN ROUTE TABLE AND BUS_STATION TABLE TO EXPORT BUS_STATION_NAME ONLY
SELECT DISTINCT
	T.DEPARTURE_ID
	,T.DEPARTURE_STATION_NAME
	,T.ARRIVAL_ID
	,BS1.BUS_STATION_NAME AS ARRIVAL_STATION_NAME
FROM (
	SELECT
		R.*
		,BS.BUS_STATION_NAME AS DEPARTURE_STATION_NAME
	FROM 
		BUS_STATION AS BS
		INNER JOIN ROUTE AS R
			ON BS.BUS_STATION_ID = R.DEPARTURE_ID)
	T
		INNER JOIN BUS_STATION AS BS1
		ON BS1.BUS_STATION_ID = T.ARRIVAL_ID;
		
		
-- JOIN ROUTE TABLE AND BUS_STATION TABLE TO EXPORT BUS_STATION_NAME AND ANOTHER INFORMATION
		
SELECT
	T.*
	,BS1.BUS_STATION_NAME AS ARRIVAL_STATION_NAME
FROM (
	SELECT
		R.*
		,BS.BUS_STATION_NAME AS DEPARTURE_STATION_NAME
	FROM 
		BUS_STATION AS BS
		INNER JOIN ROUTE AS R
			ON BS.BUS_STATION_ID = R.DEPARTURE_ID)
	T
		INNER JOIN BUS_STATION AS BS1
		ON BS1.BUS_STATION_ID = T.ARRIVAL_ID;