CREATE TABLE BUS_STATION (
 BUS_STATION_ID INTEGER NOT NULL,
 PREFECTURE VARCHAR(30) NOT NULL,
 BUS_STATION_NAME VARCHAR(100) NOT NULL
);

ALTER TABLE BUS_STATION ADD CONSTRAINT PK_BUS_STATION PRIMARY KEY (BUS_STATION_ID);


CREATE TABLE MEMBER (
 MEMBER_ID INTEGER NOT NULL,
 LOGIN_ID VARCHAR(20) NOT NULL,
 PASSWORD VARCHAR(30) NOT NULL,
 MEMBER_NAME VARCHAR(30) NOT NULL,
 MAIL_ADDRESS VARCHAR(30) NOT NULL,
 PHONE_NUMBER CHAR(15) NOT NULL
);

ALTER TABLE MEMBER ADD CONSTRAINT PK_MEMBER PRIMARY KEY (MEMBER_ID);


CREATE TABLE OPERATION_MANAGER (
 ADMINSTRATOR_ID INTEGER NOT NULL,
 LOGIN_ID VARCHAR(20) NOT NULL,
 PASSWORD VARCHAR(30) NOT NULL,
 ADMINSTRATOR_NAME VARCHAR(30) NOT NULL
);

ALTER TABLE OPERATION_MANAGER ADD CONSTRAINT PK_OPERATION_MANAGER PRIMARY KEY (ADMINSTRATOR_ID);


CREATE TABLE ROUTE (
 ROUTE_ID INTEGER NOT NULL,
 DEPARTURE_ID INTEGER NOT NULL,
 ARRIVAL_ID INTEGER NOT NULL,
 PRICE INTEGER NOT NULL,
 OPERATION_START_DATE DATE NOT NULL,
 OPERATION_END_DATE DATE,
 SCHEDULED_DEPARTURE_TIME TIMESTAMP NOT NULL,
 SCHEDULED_ARRIVAL_TIME TIMESTAMP NOT NULL
);

ALTER TABLE ROUTE ADD CONSTRAINT PK_ROUTE PRIMARY KEY (ROUTE_ID);


CREATE TABLE BUS (
 BUS_ID INTEGER NOT NULL,
 ROW_NUM INTEGER NOT NULL,
 COLUMN_NUM INTEGER NOT NULL,
 NUMBER_PLACE VARCHAR(3) NOT NULL,
 NUMBER_DIVISION VARCHAR(3) NOT NULL,
 NUMBER_KANA VARCHAR(1) NOT NULL,
 NUMBER_FIRST_HALF VARCHAR(3) NOT NULL,
 NUMBER_LATTER_HALF VARCHAR(3) NOT NULL,
 ROUTE_ID INTEGER NOT NULL
);

ALTER TABLE BUS ADD CONSTRAINT PK_BUS PRIMARY KEY (BUS_ID);


CREATE TABLE RESERVE (
 RESERVE_ID INTEGER NOT NULL,
 MEMBER_ID INTEGER NOT NULL,
 ROUTE_ID INTEGER NOT NULL,
 RESERVED_DATE TIMESTAMP NOT NULL
);

ALTER TABLE RESERVE ADD CONSTRAINT PK_RESERVE PRIMARY KEY (RESERVE_ID);


CREATE TABLE SEAT (
 SEAT_ID INTEGER NOT NULL,
 BUS_ID INTEGER NOT NULL,
 RESERVE_ID INTEGER NOT NULL
);

ALTER TABLE SEAT ADD CONSTRAINT PK_SEAT PRIMARY KEY (SEAT_ID);


--ALTER TABLE ROUTE ADD CONSTRAINT FK_ROUTE_0 FOREIGN KEY (ARRIVAL_ID) REFERENCES BUS_STATION (BUS_STATION_ID);
--ALTER TABLE ROUTE ADD CONSTRAINT FK_ROUTE_1 FOREIGN KEY (DEPARTURE_ID) REFERENCES BUS_STATION (BUS_STATION_ID);


--ALTER TABLE BUS ADD CONSTRAINT FK_BUS_0 FOREIGN KEY (ROUTE_ID) REFERENCES ROUTE (ROUTE_ID);


--ALTER TABLE RESERVE ADD CONSTRAINT FK_RESERVE_0 FOREIGN KEY (MEMBER_ID) REFERENCES MEMBER (MEMBER_ID);
--ALTER TABLE RESERVE ADD CONSTRAINT FK_RESERVE_1 FOREIGN KEY (ROUTE_ID) REFERENCES ROUTE (ROUTE_ID);


--ALTER TABLE SEAT ADD CONSTRAINT FK_SEAT_0 FOREIGN KEY (RESERVE_ID) REFERENCES RESERVE (RESERVE_ID);
--ALTER TABLE SEAT ADD CONSTRAINT FK_SEAT_1 FOREIGN KEY (BUS_ID) REFERENCES BUS (BUS_ID);


