package vn.com.vti.bus.entity;

public class Bus {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.bus.bus_id
     *
     * @mbg.generated Fri Oct 28 23:04:58 JST 2022
     */
    private Integer busId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.bus.row_num
     *
     * @mbg.generated Fri Oct 28 23:04:58 JST 2022
     */
    private Integer rowNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.bus.column_num
     *
     * @mbg.generated Fri Oct 28 23:04:58 JST 2022
     */
    private Integer columnNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.bus.number_place
     *
     * @mbg.generated Fri Oct 28 23:04:58 JST 2022
     */
    private String numberPlace;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.bus.number_division
     *
     * @mbg.generated Fri Oct 28 23:04:58 JST 2022
     */
    private String numberDivision;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.bus.number_kana
     *
     * @mbg.generated Fri Oct 28 23:04:58 JST 2022
     */
    private String numberKana;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.bus.number_first_half
     *
     * @mbg.generated Fri Oct 28 23:04:58 JST 2022
     */
    private String numberFirstHalf;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.bus.number_latter_half
     *
     * @mbg.generated Fri Oct 28 23:04:58 JST 2022
     */
    private String numberLatterHalf;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.bus.bus_id
     *
     * @return the value of public.bus.bus_id
     *
     * @mbg.generated Fri Oct 28 23:04:58 JST 2022
     * 
     * 
     */
    
    public String getNumberPlate(){
        return numberPlace+numberDivision+numberKana+numberFirstHalf+"-"+numberLatterHalf;
    	
    }
    public Integer getBusId() {
        return busId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.bus.bus_id
     *
     * @param busId the value for public.bus.bus_id
     *
     * @mbg.generated Fri Oct 28 23:04:58 JST 2022
     */
    public void setBusId(Integer busId) {
        this.busId = busId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.bus.row_num
     *
     * @return the value of public.bus.row_num
     *
     * @mbg.generated Fri Oct 28 23:04:58 JST 2022
     */
    public Integer getRowNum() {
        return rowNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.bus.row_num
     *
     * @param rowNum the value for public.bus.row_num
     *
     * @mbg.generated Fri Oct 28 23:04:58 JST 2022
     */
    public void setRowNum(Integer rowNum) {
        this.rowNum = rowNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.bus.column_num
     *
     * @return the value of public.bus.column_num
     *
     * @mbg.generated Fri Oct 28 23:04:58 JST 2022
     */
    public Integer getColumnNum() {
        return columnNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.bus.column_num
     *
     * @param columnNum the value for public.bus.column_num
     *
     * @mbg.generated Fri Oct 28 23:04:58 JST 2022
     */
    public void setColumnNum(Integer columnNum) {
        this.columnNum = columnNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.bus.number_place
     *
     * @return the value of public.bus.number_place
     *
     * @mbg.generated Fri Oct 28 23:04:58 JST 2022
     */
    public String getNumberPlace() {
        return numberPlace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.bus.number_place
     *
     * @param numberPlace the value for public.bus.number_place
     *
     * @mbg.generated Fri Oct 28 23:04:58 JST 2022
     */
    public void setNumberPlace(String numberPlace) {
        this.numberPlace = numberPlace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.bus.number_division
     *
     * @return the value of public.bus.number_division
     *
     * @mbg.generated Fri Oct 28 23:04:58 JST 2022
     */
    public String getNumberDivision() {
        return numberDivision;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.bus.number_division
     *
     * @param numberDivision the value for public.bus.number_division
     *
     * @mbg.generated Fri Oct 28 23:04:58 JST 2022
     */
    public void setNumberDivision(String numberDivision) {
        this.numberDivision = numberDivision;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.bus.number_kana
     *
     * @return the value of public.bus.number_kana
     *
     * @mbg.generated Fri Oct 28 23:04:58 JST 2022
     */
    public String getNumberKana() {
        return numberKana;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.bus.number_kana
     *
     * @param numberKana the value for public.bus.number_kana
     *
     * @mbg.generated Fri Oct 28 23:04:58 JST 2022
     */
    public void setNumberKana(String numberKana) {
        this.numberKana = numberKana;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.bus.number_first_half
     *
     * @return the value of public.bus.number_first_half
     *
     * @mbg.generated Fri Oct 28 23:04:58 JST 2022
     */
    public String getNumberFirstHalf() {
        return numberFirstHalf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.bus.number_first_half
     *
     * @param numberFirstHalf the value for public.bus.number_first_half
     *
     * @mbg.generated Fri Oct 28 23:04:58 JST 2022
     */
    public void setNumberFirstHalf(String numberFirstHalf) {
        this.numberFirstHalf = numberFirstHalf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.bus.number_latter_half
     *
     * @return the value of public.bus.number_latter_half
     *
     * @mbg.generated Fri Oct 28 23:04:58 JST 2022
     */
    public String getNumberLatterHalf() {
        return numberLatterHalf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.bus.number_latter_half
     *
     * @param numberLatterHalf the value for public.bus.number_latter_half
     *
     * @mbg.generated Fri Oct 28 23:04:58 JST 2022
     */
    public void setNumberLatterHalf(String numberLatterHalf) {
        this.numberLatterHalf = numberLatterHalf;
    }
}