package vn.com.vti.bus.entity;

public class BusStop {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.bus_stop.id
     *
     * @mbg.generated Tue Jun 02 05:35:19 JST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.bus_stop.name
     *
     * @mbg.generated Tue Jun 02 05:35:19 JST 2020
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.bus_stop.id
     *
     * @return the value of public.bus_stop.id
     *
     * @mbg.generated Tue Jun 02 05:35:19 JST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.bus_stop.id
     *
     * @param id the value for public.bus_stop.id
     *
     * @mbg.generated Tue Jun 02 05:35:19 JST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.bus_stop.name
     *
     * @return the value of public.bus_stop.name
     *
     * @mbg.generated Tue Jun 02 05:35:19 JST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.bus_stop.name
     *
     * @param name the value for public.bus_stop.name
     *
     * @mbg.generated Tue Jun 02 05:35:19 JST 2020
     */
    public void setName(String name) {
        this.name = name;
    }
}