package vn.com.vti.bus.entity;

public class BusStation {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.bus_station.bus_station_id
     *
     * @mbg.generated Fri Oct 28 23:10:12 JST 2022
     */
    private Integer busStationId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.bus_station.prefecture
     *
     * @mbg.generated Fri Oct 28 23:10:12 JST 2022
     */
    private String prefecture;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.bus_station.bus_station_name
     *
     * @mbg.generated Fri Oct 28 23:10:12 JST 2022
     */
    private String busStationName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.bus_station.bus_station_id
     *
     * @return the value of public.bus_station.bus_station_id
     *
     * @mbg.generated Fri Oct 28 23:10:12 JST 2022
     */
    public Integer getBusStationId() {
        return busStationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.bus_station.bus_station_id
     *
     * @param busStationId the value for public.bus_station.bus_station_id
     *
     * @mbg.generated Fri Oct 28 23:10:12 JST 2022
     */
    public void setBusStationId(Integer busStationId) {
        this.busStationId = busStationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.bus_station.prefecture
     *
     * @return the value of public.bus_station.prefecture
     *
     * @mbg.generated Fri Oct 28 23:10:12 JST 2022
     */
    public String getPrefecture() {
        return prefecture;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.bus_station.prefecture
     *
     * @param prefecture the value for public.bus_station.prefecture
     *
     * @mbg.generated Fri Oct 28 23:10:12 JST 2022
     */
    public void setPrefecture(String prefecture) {
        this.prefecture = prefecture;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.bus_station.bus_station_name
     *
     * @return the value of public.bus_station.bus_station_name
     *
     * @mbg.generated Fri Oct 28 23:10:12 JST 2022
     */
    public String getBusStationName() {
        return busStationName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.bus_station.bus_station_name
     *
     * @param busStationName the value for public.bus_station.bus_station_name
     *
     * @mbg.generated Fri Oct 28 23:10:12 JST 2022
     */
    public void setBusStationName(String busStationName) {
        this.busStationName = busStationName;
    }
}