package vn.com.vti.bus.entity;

public class Manager {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.manager.id
     *
     * @mbg.generated Tue Jun 02 05:35:19 JST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.manager.login_id
     *
     * @mbg.generated Tue Jun 02 05:35:19 JST 2020
     */
    private String loginId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.manager.password
     *
     * @mbg.generated Tue Jun 02 05:35:19 JST 2020
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.manager.name
     *
     * @mbg.generated Tue Jun 02 05:35:19 JST 2020
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.manager.id
     *
     * @return the value of public.manager.id
     *
     * @mbg.generated Tue Jun 02 05:35:19 JST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.manager.id
     *
     * @param id the value for public.manager.id
     *
     * @mbg.generated Tue Jun 02 05:35:19 JST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.manager.login_id
     *
     * @return the value of public.manager.login_id
     *
     * @mbg.generated Tue Jun 02 05:35:19 JST 2020
     */
    public String getLoginId() {
        return loginId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.manager.login_id
     *
     * @param loginId the value for public.manager.login_id
     *
     * @mbg.generated Tue Jun 02 05:35:19 JST 2020
     */
    public void setLoginId(String loginId) {
        this.loginId = loginId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.manager.password
     *
     * @return the value of public.manager.password
     *
     * @mbg.generated Tue Jun 02 05:35:19 JST 2020
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.manager.password
     *
     * @param password the value for public.manager.password
     *
     * @mbg.generated Tue Jun 02 05:35:19 JST 2020
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.manager.name
     *
     * @return the value of public.manager.name
     *
     * @mbg.generated Tue Jun 02 05:35:19 JST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.manager.name
     *
     * @param name the value for public.manager.name
     *
     * @mbg.generated Tue Jun 02 05:35:19 JST 2020
     */
    public void setName(String name) {
        this.name = name;
    }
}