package vn.com.vti.bus.entity;

public class Member {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.member.member_id
     *
     * @mbg.generated Fri Oct 28 23:10:12 JST 2022
     */
    private Integer memberId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.member.login_id
     *
     * @mbg.generated Fri Oct 28 23:10:12 JST 2022
     */
    private String loginId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.member.password
     *
     * @mbg.generated Fri Oct 28 23:10:12 JST 2022
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.member.member_name
     *
     * @mbg.generated Fri Oct 28 23:10:12 JST 2022
     */
    private String memberName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.member.mail_address
     *
     * @mbg.generated Fri Oct 28 23:10:12 JST 2022
     */
    private String mailAddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.member.phone_number
     *
     * @mbg.generated Fri Oct 28 23:10:12 JST 2022
     */
    private String phoneNumber;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.member.member_id
     *
     * @return the value of public.member.member_id
     *
     * @mbg.generated Fri Oct 28 23:10:12 JST 2022
     */
    public Integer getMemberId() {
        return memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.member.member_id
     *
     * @param memberId the value for public.member.member_id
     *
     * @mbg.generated Fri Oct 28 23:10:12 JST 2022
     */
    public void setMemberId(Integer memberId) {
        this.memberId = memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.member.login_id
     *
     * @return the value of public.member.login_id
     *
     * @mbg.generated Fri Oct 28 23:10:12 JST 2022
     */
    public String getLoginId() {
        return loginId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.member.login_id
     *
     * @param loginId the value for public.member.login_id
     *
     * @mbg.generated Fri Oct 28 23:10:12 JST 2022
     */
    public void setLoginId(String loginId) {
        this.loginId = loginId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.member.password
     *
     * @return the value of public.member.password
     *
     * @mbg.generated Fri Oct 28 23:10:12 JST 2022
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.member.password
     *
     * @param password the value for public.member.password
     *
     * @mbg.generated Fri Oct 28 23:10:12 JST 2022
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.member.member_name
     *
     * @return the value of public.member.member_name
     *
     * @mbg.generated Fri Oct 28 23:10:12 JST 2022
     */
    public String getMemberName() {
        return memberName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.member.member_name
     *
     * @param memberName the value for public.member.member_name
     *
     * @mbg.generated Fri Oct 28 23:10:12 JST 2022
     */
    public void setMemberName(String memberName) {
        this.memberName = memberName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.member.mail_address
     *
     * @return the value of public.member.mail_address
     *
     * @mbg.generated Fri Oct 28 23:10:12 JST 2022
     */
    public String getMailAddress() {
        return mailAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.member.mail_address
     *
     * @param mailAddress the value for public.member.mail_address
     *
     * @mbg.generated Fri Oct 28 23:10:12 JST 2022
     */
    public void setMailAddress(String mailAddress) {
        this.mailAddress = mailAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.member.phone_number
     *
     * @return the value of public.member.phone_number
     *
     * @mbg.generated Fri Oct 28 23:10:12 JST 2022
     */
    public String getPhoneNumber() {
        return phoneNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.member.phone_number
     *
     * @param phoneNumber the value for public.member.phone_number
     *
     * @mbg.generated Fri Oct 28 23:10:12 JST 2022
     */
    public void setPhoneNumber(String phoneNumber) {
        this.phoneNumber = phoneNumber;
    }
}