package vn.com.vti.bus.entity;

import java.util.ArrayList;
import java.util.List;

public class OperationManagerExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table public.operation_manager
     *
     * @mbg.generated Fri Oct 28 23:10:12 JST 2022
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table public.operation_manager
     *
     * @mbg.generated Fri Oct 28 23:10:12 JST 2022
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table public.operation_manager
     *
     * @mbg.generated Fri Oct 28 23:10:12 JST 2022
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.operation_manager
     *
     * @mbg.generated Fri Oct 28 23:10:12 JST 2022
     */
    public OperationManagerExample() {
        oredCriteria = new ArrayList<>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.operation_manager
     *
     * @mbg.generated Fri Oct 28 23:10:12 JST 2022
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.operation_manager
     *
     * @mbg.generated Fri Oct 28 23:10:12 JST 2022
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.operation_manager
     *
     * @mbg.generated Fri Oct 28 23:10:12 JST 2022
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.operation_manager
     *
     * @mbg.generated Fri Oct 28 23:10:12 JST 2022
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.operation_manager
     *
     * @mbg.generated Fri Oct 28 23:10:12 JST 2022
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.operation_manager
     *
     * @mbg.generated Fri Oct 28 23:10:12 JST 2022
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.operation_manager
     *
     * @mbg.generated Fri Oct 28 23:10:12 JST 2022
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.operation_manager
     *
     * @mbg.generated Fri Oct 28 23:10:12 JST 2022
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.operation_manager
     *
     * @mbg.generated Fri Oct 28 23:10:12 JST 2022
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.operation_manager
     *
     * @mbg.generated Fri Oct 28 23:10:12 JST 2022
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table public.operation_manager
     *
     * @mbg.generated Fri Oct 28 23:10:12 JST 2022
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andAdminstratorIdIsNull() {
            addCriterion("adminstrator_id is null");
            return (Criteria) this;
        }

        public Criteria andAdminstratorIdIsNotNull() {
            addCriterion("adminstrator_id is not null");
            return (Criteria) this;
        }

        public Criteria andAdminstratorIdEqualTo(Integer value) {
            addCriterion("adminstrator_id =", value, "adminstratorId");
            return (Criteria) this;
        }

        public Criteria andAdminstratorIdNotEqualTo(Integer value) {
            addCriterion("adminstrator_id <>", value, "adminstratorId");
            return (Criteria) this;
        }

        public Criteria andAdminstratorIdGreaterThan(Integer value) {
            addCriterion("adminstrator_id >", value, "adminstratorId");
            return (Criteria) this;
        }

        public Criteria andAdminstratorIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("adminstrator_id >=", value, "adminstratorId");
            return (Criteria) this;
        }

        public Criteria andAdminstratorIdLessThan(Integer value) {
            addCriterion("adminstrator_id <", value, "adminstratorId");
            return (Criteria) this;
        }

        public Criteria andAdminstratorIdLessThanOrEqualTo(Integer value) {
            addCriterion("adminstrator_id <=", value, "adminstratorId");
            return (Criteria) this;
        }

        public Criteria andAdminstratorIdIn(List<Integer> values) {
            addCriterion("adminstrator_id in", values, "adminstratorId");
            return (Criteria) this;
        }

        public Criteria andAdminstratorIdNotIn(List<Integer> values) {
            addCriterion("adminstrator_id not in", values, "adminstratorId");
            return (Criteria) this;
        }

        public Criteria andAdminstratorIdBetween(Integer value1, Integer value2) {
            addCriterion("adminstrator_id between", value1, value2, "adminstratorId");
            return (Criteria) this;
        }

        public Criteria andAdminstratorIdNotBetween(Integer value1, Integer value2) {
            addCriterion("adminstrator_id not between", value1, value2, "adminstratorId");
            return (Criteria) this;
        }

        public Criteria andLoginIdIsNull() {
            addCriterion("login_id is null");
            return (Criteria) this;
        }

        public Criteria andLoginIdIsNotNull() {
            addCriterion("login_id is not null");
            return (Criteria) this;
        }

        public Criteria andLoginIdEqualTo(String value) {
            addCriterion("login_id =", value, "loginId");
            return (Criteria) this;
        }

        public Criteria andLoginIdNotEqualTo(String value) {
            addCriterion("login_id <>", value, "loginId");
            return (Criteria) this;
        }

        public Criteria andLoginIdGreaterThan(String value) {
            addCriterion("login_id >", value, "loginId");
            return (Criteria) this;
        }

        public Criteria andLoginIdGreaterThanOrEqualTo(String value) {
            addCriterion("login_id >=", value, "loginId");
            return (Criteria) this;
        }

        public Criteria andLoginIdLessThan(String value) {
            addCriterion("login_id <", value, "loginId");
            return (Criteria) this;
        }

        public Criteria andLoginIdLessThanOrEqualTo(String value) {
            addCriterion("login_id <=", value, "loginId");
            return (Criteria) this;
        }

        public Criteria andLoginIdLike(String value) {
            addCriterion("login_id like", value, "loginId");
            return (Criteria) this;
        }

        public Criteria andLoginIdNotLike(String value) {
            addCriterion("login_id not like", value, "loginId");
            return (Criteria) this;
        }

        public Criteria andLoginIdIn(List<String> values) {
            addCriterion("login_id in", values, "loginId");
            return (Criteria) this;
        }

        public Criteria andLoginIdNotIn(List<String> values) {
            addCriterion("login_id not in", values, "loginId");
            return (Criteria) this;
        }

        public Criteria andLoginIdBetween(String value1, String value2) {
            addCriterion("login_id between", value1, value2, "loginId");
            return (Criteria) this;
        }

        public Criteria andLoginIdNotBetween(String value1, String value2) {
            addCriterion("login_id not between", value1, value2, "loginId");
            return (Criteria) this;
        }

        public Criteria andPasswordIsNull() {
            addCriterion("password is null");
            return (Criteria) this;
        }

        public Criteria andPasswordIsNotNull() {
            addCriterion("password is not null");
            return (Criteria) this;
        }

        public Criteria andPasswordEqualTo(String value) {
            addCriterion("password =", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordNotEqualTo(String value) {
            addCriterion("password <>", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordGreaterThan(String value) {
            addCriterion("password >", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordGreaterThanOrEqualTo(String value) {
            addCriterion("password >=", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordLessThan(String value) {
            addCriterion("password <", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordLessThanOrEqualTo(String value) {
            addCriterion("password <=", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordLike(String value) {
            addCriterion("password like", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordNotLike(String value) {
            addCriterion("password not like", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordIn(List<String> values) {
            addCriterion("password in", values, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordNotIn(List<String> values) {
            addCriterion("password not in", values, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordBetween(String value1, String value2) {
            addCriterion("password between", value1, value2, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordNotBetween(String value1, String value2) {
            addCriterion("password not between", value1, value2, "password");
            return (Criteria) this;
        }

        public Criteria andAdminstratorNameIsNull() {
            addCriterion("adminstrator_name is null");
            return (Criteria) this;
        }

        public Criteria andAdminstratorNameIsNotNull() {
            addCriterion("adminstrator_name is not null");
            return (Criteria) this;
        }

        public Criteria andAdminstratorNameEqualTo(String value) {
            addCriterion("adminstrator_name =", value, "adminstratorName");
            return (Criteria) this;
        }

        public Criteria andAdminstratorNameNotEqualTo(String value) {
            addCriterion("adminstrator_name <>", value, "adminstratorName");
            return (Criteria) this;
        }

        public Criteria andAdminstratorNameGreaterThan(String value) {
            addCriterion("adminstrator_name >", value, "adminstratorName");
            return (Criteria) this;
        }

        public Criteria andAdminstratorNameGreaterThanOrEqualTo(String value) {
            addCriterion("adminstrator_name >=", value, "adminstratorName");
            return (Criteria) this;
        }

        public Criteria andAdminstratorNameLessThan(String value) {
            addCriterion("adminstrator_name <", value, "adminstratorName");
            return (Criteria) this;
        }

        public Criteria andAdminstratorNameLessThanOrEqualTo(String value) {
            addCriterion("adminstrator_name <=", value, "adminstratorName");
            return (Criteria) this;
        }

        public Criteria andAdminstratorNameLike(String value) {
            addCriterion("adminstrator_name like", value, "adminstratorName");
            return (Criteria) this;
        }

        public Criteria andAdminstratorNameNotLike(String value) {
            addCriterion("adminstrator_name not like", value, "adminstratorName");
            return (Criteria) this;
        }

        public Criteria andAdminstratorNameIn(List<String> values) {
            addCriterion("adminstrator_name in", values, "adminstratorName");
            return (Criteria) this;
        }

        public Criteria andAdminstratorNameNotIn(List<String> values) {
            addCriterion("adminstrator_name not in", values, "adminstratorName");
            return (Criteria) this;
        }

        public Criteria andAdminstratorNameBetween(String value1, String value2) {
            addCriterion("adminstrator_name between", value1, value2, "adminstratorName");
            return (Criteria) this;
        }

        public Criteria andAdminstratorNameNotBetween(String value1, String value2) {
            addCriterion("adminstrator_name not between", value1, value2, "adminstratorName");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table public.operation_manager
     *
     * @mbg.generated do_not_delete_during_merge Fri Oct 28 23:10:12 JST 2022
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table public.operation_manager
     *
     * @mbg.generated Fri Oct 28 23:10:12 JST 2022
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}