package vn.com.vti.bus.entity;

public class OperationManager {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.operation_manager.adminstrator_id
     *
     * @mbg.generated Fri Oct 28 23:10:12 JST 2022
     */
    private Integer adminstratorId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.operation_manager.login_id
     *
     * @mbg.generated Fri Oct 28 23:10:12 JST 2022
     */
    private String loginId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.operation_manager.password
     *
     * @mbg.generated Fri Oct 28 23:10:12 JST 2022
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.operation_manager.adminstrator_name
     *
     * @mbg.generated Fri Oct 28 23:10:12 JST 2022
     */
    private String adminstratorName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.operation_manager.adminstrator_id
     *
     * @return the value of public.operation_manager.adminstrator_id
     *
     * @mbg.generated Fri Oct 28 23:10:12 JST 2022
     */
    public Integer getAdminstratorId() {
        return adminstratorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.operation_manager.adminstrator_id
     *
     * @param adminstratorId the value for public.operation_manager.adminstrator_id
     *
     * @mbg.generated Fri Oct 28 23:10:12 JST 2022
     */
    public void setAdminstratorId(Integer adminstratorId) {
        this.adminstratorId = adminstratorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.operation_manager.login_id
     *
     * @return the value of public.operation_manager.login_id
     *
     * @mbg.generated Fri Oct 28 23:10:12 JST 2022
     */
    public String getLoginId() {
        return loginId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.operation_manager.login_id
     *
     * @param loginId the value for public.operation_manager.login_id
     *
     * @mbg.generated Fri Oct 28 23:10:12 JST 2022
     */
    public void setLoginId(String loginId) {
        this.loginId = loginId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.operation_manager.password
     *
     * @return the value of public.operation_manager.password
     *
     * @mbg.generated Fri Oct 28 23:10:12 JST 2022
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.operation_manager.password
     *
     * @param password the value for public.operation_manager.password
     *
     * @mbg.generated Fri Oct 28 23:10:12 JST 2022
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.operation_manager.adminstrator_name
     *
     * @return the value of public.operation_manager.adminstrator_name
     *
     * @mbg.generated Fri Oct 28 23:10:12 JST 2022
     */
    public String getAdminstratorName() {
        return adminstratorName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.operation_manager.adminstrator_name
     *
     * @param adminstratorName the value for public.operation_manager.adminstrator_name
     *
     * @mbg.generated Fri Oct 28 23:10:12 JST 2022
     */
    public void setAdminstratorName(String adminstratorName) {
        this.adminstratorName = adminstratorName;
    }
}