package vn.com.vti.bus.entity;

import java.util.Date;

public class Reserve {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.reserve.reserve_id
     *
     * @mbg.generated Fri Oct 28 23:10:12 JST 2022
     */
    private Integer reserveId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.reserve.member_id
     *
     * @mbg.generated Fri Oct 28 23:10:12 JST 2022
     */
    private Integer memberId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.reserve.route_id
     *
     * @mbg.generated Fri Oct 28 23:10:12 JST 2022
     */
    private Integer routeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.reserve.reserved_date
     *
     * @mbg.generated Fri Oct 28 23:10:12 JST 2022
     */
    private Date reservedDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.reserve.departure_date
     *
     * @mbg.generated Fri Oct 28 23:10:12 JST 2022
     */
    private Date departureDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.reserve.reserve_id
     *
     * @return the value of public.reserve.reserve_id
     *
     * @mbg.generated Fri Oct 28 23:10:12 JST 2022
     */
    public Integer getReserveId() {
        return reserveId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.reserve.reserve_id
     *
     * @param reserveId the value for public.reserve.reserve_id
     *
     * @mbg.generated Fri Oct 28 23:10:12 JST 2022
     */
    public void setReserveId(Integer reserveId) {
        this.reserveId = reserveId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.reserve.member_id
     *
     * @return the value of public.reserve.member_id
     *
     * @mbg.generated Fri Oct 28 23:10:12 JST 2022
     */
    public Integer getMemberId() {
        return memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.reserve.member_id
     *
     * @param memberId the value for public.reserve.member_id
     *
     * @mbg.generated Fri Oct 28 23:10:12 JST 2022
     */
    public void setMemberId(Integer memberId) {
        this.memberId = memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.reserve.route_id
     *
     * @return the value of public.reserve.route_id
     *
     * @mbg.generated Fri Oct 28 23:10:12 JST 2022
     */
    public Integer getRouteId() {
        return routeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.reserve.route_id
     *
     * @param routeId the value for public.reserve.route_id
     *
     * @mbg.generated Fri Oct 28 23:10:12 JST 2022
     */
    public void setRouteId(Integer routeId) {
        this.routeId = routeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.reserve.reserved_date
     *
     * @return the value of public.reserve.reserved_date
     *
     * @mbg.generated Fri Oct 28 23:10:12 JST 2022
     */
    public Date getReservedDate() {
        return reservedDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.reserve.reserved_date
     *
     * @param reservedDate the value for public.reserve.reserved_date
     *
     * @mbg.generated Fri Oct 28 23:10:12 JST 2022
     */
    public void setReservedDate(Date reservedDate) {
        this.reservedDate = reservedDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.reserve.departure_date
     *
     * @return the value of public.reserve.departure_date
     *
     * @mbg.generated Fri Oct 28 23:10:12 JST 2022
     */
    public Date getDepartureDate() {
        return departureDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.reserve.departure_date
     *
     * @param departureDate the value for public.reserve.departure_date
     *
     * @mbg.generated Fri Oct 28 23:10:12 JST 2022
     */
    public void setDepartureDate(Date departureDate) {
        this.departureDate = departureDate;
    }
}