package vn.com.vti.bus.entity;

import java.security.Timestamp;
import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class RouteExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table public.route
     *
     * @mbg.generated Fri Oct 28 23:10:12 JST 2022
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table public.route
     *
     * @mbg.generated Fri Oct 28 23:10:12 JST 2022
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table public.route
     *
     * @mbg.generated Fri Oct 28 23:10:12 JST 2022
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.route
     *
     * @mbg.generated Fri Oct 28 23:10:12 JST 2022
     */
    public RouteExample() {
        oredCriteria = new ArrayList<>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.route
     *
     * @mbg.generated Fri Oct 28 23:10:12 JST 2022
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.route
     *
     * @mbg.generated Fri Oct 28 23:10:12 JST 2022
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.route
     *
     * @mbg.generated Fri Oct 28 23:10:12 JST 2022
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.route
     *
     * @mbg.generated Fri Oct 28 23:10:12 JST 2022
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.route
     *
     * @mbg.generated Fri Oct 28 23:10:12 JST 2022
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.route
     *
     * @mbg.generated Fri Oct 28 23:10:12 JST 2022
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.route
     *
     * @mbg.generated Fri Oct 28 23:10:12 JST 2022
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.route
     *
     * @mbg.generated Fri Oct 28 23:10:12 JST 2022
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.route
     *
     * @mbg.generated Fri Oct 28 23:10:12 JST 2022
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.route
     *
     * @mbg.generated Fri Oct 28 23:10:12 JST 2022
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table public.route
     *
     * @mbg.generated Fri Oct 28 23:10:12 JST 2022
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        protected void addCriterionForJDBCDate(String condition, Date value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value.getTime()), property);
        }

        protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            List<java.sql.Date> dateList = new ArrayList<>();
            Iterator<Date> iter = values.iterator();
            while (iter.hasNext()) {
                dateList.add(new java.sql.Date(iter.next().getTime()));
            }
            addCriterion(condition, dateList, property);
        }

        protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
        }

        public Criteria andRouteIdIsNull() {
            addCriterion("route_id is null");
            return (Criteria) this;
        }

        public Criteria andRouteIdIsNotNull() {
            addCriterion("route_id is not null");
            return (Criteria) this;
        }

        public Criteria andRouteIdEqualTo(Integer value) {
            addCriterion("route_id =", value, "routeId");
            return (Criteria) this;
        }

        public Criteria andRouteIdNotEqualTo(Integer value) {
            addCriterion("route_id <>", value, "routeId");
            return (Criteria) this;
        }

        public Criteria andRouteIdGreaterThan(Integer value) {
            addCriterion("route_id >", value, "routeId");
            return (Criteria) this;
        }

        public Criteria andRouteIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("route_id >=", value, "routeId");
            return (Criteria) this;
        }

        public Criteria andRouteIdLessThan(Integer value) {
            addCriterion("route_id <", value, "routeId");
            return (Criteria) this;
        }

        public Criteria andRouteIdLessThanOrEqualTo(Integer value) {
            addCriterion("route_id <=", value, "routeId");
            return (Criteria) this;
        }

        public Criteria andRouteIdIn(List<Integer> values) {
            addCriterion("route_id in", values, "routeId");
            return (Criteria) this;
        }

        public Criteria andRouteIdNotIn(List<Integer> values) {
            addCriterion("route_id not in", values, "routeId");
            return (Criteria) this;
        }

        public Criteria andRouteIdBetween(Integer value1, Integer value2) {
            addCriterion("route_id between", value1, value2, "routeId");
            return (Criteria) this;
        }

        public Criteria andRouteIdNotBetween(Integer value1, Integer value2) {
            addCriterion("route_id not between", value1, value2, "routeId");
            return (Criteria) this;
        }

        public Criteria andDepartureIdIsNull() {
            addCriterion("departure_id is null");
            return (Criteria) this;
        }

        public Criteria andDepartureIdIsNotNull() {
            addCriterion("departure_id is not null");
            return (Criteria) this;
        }

        public Criteria andDepartureIdEqualTo(Integer value) {
            addCriterion("departure_id =", value, "departureId");
            return (Criteria) this;
        }

        public Criteria andDepartureIdNotEqualTo(Integer value) {
            addCriterion("departure_id <>", value, "departureId");
            return (Criteria) this;
        }

        public Criteria andDepartureIdGreaterThan(Integer value) {
            addCriterion("departure_id >", value, "departureId");
            return (Criteria) this;
        }

        public Criteria andDepartureIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("departure_id >=", value, "departureId");
            return (Criteria) this;
        }

        public Criteria andDepartureIdLessThan(Integer value) {
            addCriterion("departure_id <", value, "departureId");
            return (Criteria) this;
        }

        public Criteria andDepartureIdLessThanOrEqualTo(Integer value) {
            addCriterion("departure_id <=", value, "departureId");
            return (Criteria) this;
        }

        public Criteria andDepartureIdIn(List<Integer> values) {
            addCriterion("departure_id in", values, "departureId");
            return (Criteria) this;
        }

        public Criteria andDepartureIdNotIn(List<Integer> values) {
            addCriterion("departure_id not in", values, "departureId");
            return (Criteria) this;
        }

        public Criteria andDepartureIdBetween(Integer value1, Integer value2) {
            addCriterion("departure_id between", value1, value2, "departureId");
            return (Criteria) this;
        }

        public Criteria andDepartureIdNotBetween(Integer value1, Integer value2) {
            addCriterion("departure_id not between", value1, value2, "departureId");
            return (Criteria) this;
        }

        public Criteria andArrivalIdIsNull() {
            addCriterion("arrival_id is null");
            return (Criteria) this;
        }

        public Criteria andArrivalIdIsNotNull() {
            addCriterion("arrival_id is not null");
            return (Criteria) this;
        }

        public Criteria andArrivalIdEqualTo(Integer value) {
            addCriterion("arrival_id =", value, "arrivalId");
            return (Criteria) this;
        }

        public Criteria andArrivalIdNotEqualTo(Integer value) {
            addCriterion("arrival_id <>", value, "arrivalId");
            return (Criteria) this;
        }

        public Criteria andArrivalIdGreaterThan(Integer value) {
            addCriterion("arrival_id >", value, "arrivalId");
            return (Criteria) this;
        }

        public Criteria andArrivalIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("arrival_id >=", value, "arrivalId");
            return (Criteria) this;
        }

        public Criteria andArrivalIdLessThan(Integer value) {
            addCriterion("arrival_id <", value, "arrivalId");
            return (Criteria) this;
        }

        public Criteria andArrivalIdLessThanOrEqualTo(Integer value) {
            addCriterion("arrival_id <=", value, "arrivalId");
            return (Criteria) this;
        }

        public Criteria andArrivalIdIn(List<Integer> values) {
            addCriterion("arrival_id in", values, "arrivalId");
            return (Criteria) this;
        }

        public Criteria andArrivalIdNotIn(List<Integer> values) {
            addCriterion("arrival_id not in", values, "arrivalId");
            return (Criteria) this;
        }

        public Criteria andArrivalIdBetween(Integer value1, Integer value2) {
            addCriterion("arrival_id between", value1, value2, "arrivalId");
            return (Criteria) this;
        }

        public Criteria andArrivalIdNotBetween(Integer value1, Integer value2) {
            addCriterion("arrival_id not between", value1, value2, "arrivalId");
            return (Criteria) this;
        }

        public Criteria andPriceIsNull() {
            addCriterion("price is null");
            return (Criteria) this;
        }

        public Criteria andPriceIsNotNull() {
            addCriterion("price is not null");
            return (Criteria) this;
        }

        public Criteria andPriceEqualTo(Integer value) {
            addCriterion("price =", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceNotEqualTo(Integer value) {
            addCriterion("price <>", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceGreaterThan(Integer value) {
            addCriterion("price >", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceGreaterThanOrEqualTo(Integer value) {
            addCriterion("price >=", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceLessThan(Integer value) {
            addCriterion("price <", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceLessThanOrEqualTo(Integer value) {
            addCriterion("price <=", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceIn(List<Integer> values) {
            addCriterion("price in", values, "price");
            return (Criteria) this;
        }

        public Criteria andPriceNotIn(List<Integer> values) {
            addCriterion("price not in", values, "price");
            return (Criteria) this;
        }

        public Criteria andPriceBetween(Integer value1, Integer value2) {
            addCriterion("price between", value1, value2, "price");
            return (Criteria) this;
        }

        public Criteria andPriceNotBetween(Integer value1, Integer value2) {
            addCriterion("price not between", value1, value2, "price");
            return (Criteria) this;
        }

        public Criteria andBusIdIsNull() {
            addCriterion("bus_id is null");
            return (Criteria) this;
        }

        public Criteria andBusIdIsNotNull() {
            addCriterion("bus_id is not null");
            return (Criteria) this;
        }

        public Criteria andBusIdEqualTo(Integer value) {
            addCriterion("bus_id =", value, "busId");
            return (Criteria) this;
        }

        public Criteria andBusIdNotEqualTo(Integer value) {
            addCriterion("bus_id <>", value, "busId");
            return (Criteria) this;
        }

        public Criteria andBusIdGreaterThan(Integer value) {
            addCriterion("bus_id >", value, "busId");
            return (Criteria) this;
        }

        public Criteria andBusIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("bus_id >=", value, "busId");
            return (Criteria) this;
        }

        public Criteria andBusIdLessThan(Integer value) {
            addCriterion("bus_id <", value, "busId");
            return (Criteria) this;
        }

        public Criteria andBusIdLessThanOrEqualTo(Integer value) {
            addCriterion("bus_id <=", value, "busId");
            return (Criteria) this;
        }

        public Criteria andBusIdIn(List<Integer> values) {
            addCriterion("bus_id in", values, "busId");
            return (Criteria) this;
        }

        public Criteria andBusIdNotIn(List<Integer> values) {
            addCriterion("bus_id not in", values, "busId");
            return (Criteria) this;
        }

        public Criteria andBusIdBetween(Integer value1, Integer value2) {
            addCriterion("bus_id between", value1, value2, "busId");
            return (Criteria) this;
        }

        public Criteria andBusIdNotBetween(Integer value1, Integer value2) {
            addCriterion("bus_id not between", value1, value2, "busId");
            return (Criteria) this;
        }

        public Criteria andOperationStartDateIsNull() {
            addCriterion("operation_start_date is null");
            return (Criteria) this;
        }

        public Criteria andOperationStartDateIsNotNull() {
            addCriterion("operation_start_date is not null");
            return (Criteria) this;
        }

        public Criteria andOperationStartDateEqualTo(Date value) {
            addCriterionForJDBCDate("operation_start_date =", value, "operationStartDate");
            return (Criteria) this;
        }

        public Criteria andOperationStartDateNotEqualTo(Date value) {
            addCriterionForJDBCDate("operation_start_date <>", value, "operationStartDate");
            return (Criteria) this;
        }

        public Criteria andOperationStartDateGreaterThan(Date value) {
            addCriterionForJDBCDate("operation_start_date >", value, "operationStartDate");
            return (Criteria) this;
        }

        public Criteria andOperationStartDateGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("operation_start_date >=", value, "operationStartDate");
            return (Criteria) this;
        }

        public Criteria andOperationStartDateLessThan(Date value) {
            addCriterionForJDBCDate("operation_start_date <", value, "operationStartDate");
            return (Criteria) this;
        }

        public Criteria andOperationStartDateLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("operation_start_date <=", value, "operationStartDate");
            return (Criteria) this;
        }

        public Criteria andOperationStartDateIn(List<Date> values) {
            addCriterionForJDBCDate("operation_start_date in", values, "operationStartDate");
            return (Criteria) this;
        }

        public Criteria andOperationStartDateNotIn(List<Date> values) {
            addCriterionForJDBCDate("operation_start_date not in", values, "operationStartDate");
            return (Criteria) this;
        }

        public Criteria andOperationStartDateBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("operation_start_date between", value1, value2, "operationStartDate");
            return (Criteria) this;
        }

        public Criteria andOperationStartDateNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("operation_start_date not between", value1, value2, "operationStartDate");
            return (Criteria) this;
        }

        public Criteria andOperationEndDateIsNull() {
            addCriterion("operation_end_date is null");
            return (Criteria) this;
        }

        public Criteria andOperationEndDateIsNotNull() {
            addCriterion("operation_end_date is not null");
            return (Criteria) this;
        }

        public Criteria andOperationEndDateEqualTo(Date value) {
            addCriterionForJDBCDate("operation_end_date =", value, "operationEndDate");
            return (Criteria) this;
        }

        public Criteria andOperationEndDateNotEqualTo(Date value) {
            addCriterionForJDBCDate("operation_end_date <>", value, "operationEndDate");
            return (Criteria) this;
        }

        public Criteria andOperationEndDateGreaterThan(Date value) {
            addCriterionForJDBCDate("operation_end_date >", value, "operationEndDate");
            return (Criteria) this;
        }

        public Criteria andOperationEndDateGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("operation_end_date >=", value, "operationEndDate");
            return (Criteria) this;
        }

        public Criteria andOperationEndDateLessThan(Date value) {
            addCriterionForJDBCDate("operation_end_date <", value, "operationEndDate");
            return (Criteria) this;
        }

        public Criteria andOperationEndDateLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("operation_end_date <=", value, "operationEndDate");
            return (Criteria) this;
        }

        public Criteria andOperationEndDateIn(List<Date> values) {
            addCriterionForJDBCDate("operation_end_date in", values, "operationEndDate");
            return (Criteria) this;
        }

        public Criteria andOperationEndDateNotIn(List<Date> values) {
            addCriterionForJDBCDate("operation_end_date not in", values, "operationEndDate");
            return (Criteria) this;
        }

        public Criteria andOperationEndDateBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("operation_end_date between", value1, value2, "operationEndDate");
            return (Criteria) this;
        }

        public Criteria andOperationEndDateNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("operation_end_date not between", value1, value2, "operationEndDate");
            return (Criteria) this;
        }

        public Criteria andScheduledDepartureTimeIsNull() {
            addCriterion("scheduled_departure_time is null");
            return (Criteria) this;
        }

        public Criteria andScheduledDepartureTimeIsNotNull() {
            addCriterion("scheduled_departure_time is not null");
            return (Criteria) this;
        }

        public Criteria andScheduledDepartureTimeEqualTo(Timestamp timestamp) {
            addCriterion("scheduled_departure_time =", timestamp, "scheduledDepartureTime");
            return (Criteria) this;
        }

        public Criteria andScheduledDepartureTimeNotEqualTo(Date value) {
            addCriterion("scheduled_departure_time <>", value, "scheduledDepartureTime");
            return (Criteria) this;
        }

        public Criteria andScheduledDepartureTimeGreaterThan(Date value) {
            addCriterion("scheduled_departure_time >", value, "scheduledDepartureTime");
            return (Criteria) this;
        }

        public Criteria andScheduledDepartureTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("scheduled_departure_time >=", value, "scheduledDepartureTime");
            return (Criteria) this;
        }

        public Criteria andScheduledDepartureTimeLessThan(Date value) {
            addCriterion("scheduled_departure_time <", value, "scheduledDepartureTime");
            return (Criteria) this;
        }

        public Criteria andScheduledDepartureTimeLessThanOrEqualTo(Date value) {
            addCriterion("scheduled_departure_time <=", value, "scheduledDepartureTime");
            return (Criteria) this;
        }

        public Criteria andScheduledDepartureTimeIn(List<Date> values) {
            addCriterion("scheduled_departure_time in", values, "scheduledDepartureTime");
            return (Criteria) this;
        }

        public Criteria andScheduledDepartureTimeNotIn(List<Date> values) {
            addCriterion("scheduled_departure_time not in", values, "scheduledDepartureTime");
            return (Criteria) this;
        }

        public Criteria andScheduledDepartureTimeBetween(Date value1, Date value2) {
            addCriterion("scheduled_departure_time between", value1, value2, "scheduledDepartureTime");
            return (Criteria) this;
        }

        public Criteria andScheduledDepartureTimeNotBetween(Date value1, Date value2) {
            addCriterion("scheduled_departure_time not between", value1, value2, "scheduledDepartureTime");
            return (Criteria) this;
        }

        public Criteria andScheduledArrivalTimeIsNull() {
            addCriterion("scheduled_arrival_time is null");
            return (Criteria) this;
        }

        public Criteria andScheduledArrivalTimeIsNotNull() {
            addCriterion("scheduled_arrival_time is not null");
            return (Criteria) this;
        }

        public Criteria andScheduledArrivalTimeEqualTo(Timestamp timestamp) {
            addCriterion("scheduled_arrival_time =", timestamp, "scheduledArrivalTime");
            return (Criteria) this;
        }

        public Criteria andScheduledArrivalTimeNotEqualTo(Date value) {
            addCriterion("scheduled_arrival_time <>", value, "scheduledArrivalTime");
            return (Criteria) this;
        }

        public Criteria andScheduledArrivalTimeGreaterThan(Date value) {
            addCriterion("scheduled_arrival_time >", value, "scheduledArrivalTime");
            return (Criteria) this;
        }

        public Criteria andScheduledArrivalTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("scheduled_arrival_time >=", value, "scheduledArrivalTime");
            return (Criteria) this;
        }

        public Criteria andScheduledArrivalTimeLessThan(Date value) {
            addCriterion("scheduled_arrival_time <", value, "scheduledArrivalTime");
            return (Criteria) this;
        }

        public Criteria andScheduledArrivalTimeLessThanOrEqualTo(Date value) {
            addCriterion("scheduled_arrival_time <=", value, "scheduledArrivalTime");
            return (Criteria) this;
        }

        public Criteria andScheduledArrivalTimeIn(List<Date> values) {
            addCriterion("scheduled_arrival_time in", values, "scheduledArrivalTime");
            return (Criteria) this;
        }

        public Criteria andScheduledArrivalTimeNotIn(List<Date> values) {
            addCriterion("scheduled_arrival_time not in", values, "scheduledArrivalTime");
            return (Criteria) this;
        }

        public Criteria andScheduledArrivalTimeBetween(Date value1, Date value2) {
            addCriterion("scheduled_arrival_time between", value1, value2, "scheduledArrivalTime");
            return (Criteria) this;
        }

        public Criteria andScheduledArrivalTimeNotBetween(Date value1, Date value2) {
            addCriterion("scheduled_arrival_time not between", value1, value2, "scheduledArrivalTime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table public.route
     *
     * @mbg.generated do_not_delete_during_merge Fri Oct 28 23:10:12 JST 2022
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table public.route
     *
     * @mbg.generated Fri Oct 28 23:10:12 JST 2022
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}