package vn.com.vti.bus.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class RouteExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table public.route
     *
     * @mbg.generated Tue Jun 02 05:35:19 JST 2020
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table public.route
     *
     * @mbg.generated Tue Jun 02 05:35:19 JST 2020
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table public.route
     *
     * @mbg.generated Tue Jun 02 05:35:19 JST 2020
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.route
     *
     * @mbg.generated Tue Jun 02 05:35:19 JST 2020
     */
    public RouteExample() {
        oredCriteria = new ArrayList<>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.route
     *
     * @mbg.generated Tue Jun 02 05:35:19 JST 2020
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.route
     *
     * @mbg.generated Tue Jun 02 05:35:19 JST 2020
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.route
     *
     * @mbg.generated Tue Jun 02 05:35:19 JST 2020
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.route
     *
     * @mbg.generated Tue Jun 02 05:35:19 JST 2020
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.route
     *
     * @mbg.generated Tue Jun 02 05:35:19 JST 2020
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.route
     *
     * @mbg.generated Tue Jun 02 05:35:19 JST 2020
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.route
     *
     * @mbg.generated Tue Jun 02 05:35:19 JST 2020
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.route
     *
     * @mbg.generated Tue Jun 02 05:35:19 JST 2020
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.route
     *
     * @mbg.generated Tue Jun 02 05:35:19 JST 2020
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.route
     *
     * @mbg.generated Tue Jun 02 05:35:19 JST 2020
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table public.route
     *
     * @mbg.generated Tue Jun 02 05:35:19 JST 2020
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        protected void addCriterionForJDBCDate(String condition, Date value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value.getTime()), property);
        }

        protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            List<java.sql.Date> dateList = new ArrayList<>();
            Iterator<Date> iter = values.iterator();
            while (iter.hasNext()) {
                dateList.add(new java.sql.Date(iter.next().getTime()));
            }
            addCriterion(condition, dateList, property);
        }

        protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
        }

        protected void addCriterionForJDBCTime(String condition, Date value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Time(value.getTime()), property);
        }

        protected void addCriterionForJDBCTime(String condition, List<Date> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            List<java.sql.Time> timeList = new ArrayList<>();
            Iterator<Date> iter = values.iterator();
            while (iter.hasNext()) {
                timeList.add(new java.sql.Time(iter.next().getTime()));
            }
            addCriterion(condition, timeList, property);
        }

        protected void addCriterionForJDBCTime(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Time(value1.getTime()), new java.sql.Time(value2.getTime()), property);
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andDepartureBusStopIdIsNull() {
            addCriterion("departure_bus_stop_id is null");
            return (Criteria) this;
        }

        public Criteria andDepartureBusStopIdIsNotNull() {
            addCriterion("departure_bus_stop_id is not null");
            return (Criteria) this;
        }

        public Criteria andDepartureBusStopIdEqualTo(Integer value) {
            addCriterion("departure_bus_stop_id =", value, "departureBusStopId");
            return (Criteria) this;
        }

        public Criteria andDepartureBusStopIdNotEqualTo(Integer value) {
            addCriterion("departure_bus_stop_id <>", value, "departureBusStopId");
            return (Criteria) this;
        }

        public Criteria andDepartureBusStopIdGreaterThan(Integer value) {
            addCriterion("departure_bus_stop_id >", value, "departureBusStopId");
            return (Criteria) this;
        }

        public Criteria andDepartureBusStopIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("departure_bus_stop_id >=", value, "departureBusStopId");
            return (Criteria) this;
        }

        public Criteria andDepartureBusStopIdLessThan(Integer value) {
            addCriterion("departure_bus_stop_id <", value, "departureBusStopId");
            return (Criteria) this;
        }

        public Criteria andDepartureBusStopIdLessThanOrEqualTo(Integer value) {
            addCriterion("departure_bus_stop_id <=", value, "departureBusStopId");
            return (Criteria) this;
        }

        public Criteria andDepartureBusStopIdIn(List<Integer> values) {
            addCriterion("departure_bus_stop_id in", values, "departureBusStopId");
            return (Criteria) this;
        }

        public Criteria andDepartureBusStopIdNotIn(List<Integer> values) {
            addCriterion("departure_bus_stop_id not in", values, "departureBusStopId");
            return (Criteria) this;
        }

        public Criteria andDepartureBusStopIdBetween(Integer value1, Integer value2) {
            addCriterion("departure_bus_stop_id between", value1, value2, "departureBusStopId");
            return (Criteria) this;
        }

        public Criteria andDepartureBusStopIdNotBetween(Integer value1, Integer value2) {
            addCriterion("departure_bus_stop_id not between", value1, value2, "departureBusStopId");
            return (Criteria) this;
        }

        public Criteria andArrivalBusStopIdIsNull() {
            addCriterion("arrival_bus_stop_id is null");
            return (Criteria) this;
        }

        public Criteria andArrivalBusStopIdIsNotNull() {
            addCriterion("arrival_bus_stop_id is not null");
            return (Criteria) this;
        }

        public Criteria andArrivalBusStopIdEqualTo(Integer value) {
            addCriterion("arrival_bus_stop_id =", value, "arrivalBusStopId");
            return (Criteria) this;
        }

        public Criteria andArrivalBusStopIdNotEqualTo(Integer value) {
            addCriterion("arrival_bus_stop_id <>", value, "arrivalBusStopId");
            return (Criteria) this;
        }

        public Criteria andArrivalBusStopIdGreaterThan(Integer value) {
            addCriterion("arrival_bus_stop_id >", value, "arrivalBusStopId");
            return (Criteria) this;
        }

        public Criteria andArrivalBusStopIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("arrival_bus_stop_id >=", value, "arrivalBusStopId");
            return (Criteria) this;
        }

        public Criteria andArrivalBusStopIdLessThan(Integer value) {
            addCriterion("arrival_bus_stop_id <", value, "arrivalBusStopId");
            return (Criteria) this;
        }

        public Criteria andArrivalBusStopIdLessThanOrEqualTo(Integer value) {
            addCriterion("arrival_bus_stop_id <=", value, "arrivalBusStopId");
            return (Criteria) this;
        }

        public Criteria andArrivalBusStopIdIn(List<Integer> values) {
            addCriterion("arrival_bus_stop_id in", values, "arrivalBusStopId");
            return (Criteria) this;
        }

        public Criteria andArrivalBusStopIdNotIn(List<Integer> values) {
            addCriterion("arrival_bus_stop_id not in", values, "arrivalBusStopId");
            return (Criteria) this;
        }

        public Criteria andArrivalBusStopIdBetween(Integer value1, Integer value2) {
            addCriterion("arrival_bus_stop_id between", value1, value2, "arrivalBusStopId");
            return (Criteria) this;
        }

        public Criteria andArrivalBusStopIdNotBetween(Integer value1, Integer value2) {
            addCriterion("arrival_bus_stop_id not between", value1, value2, "arrivalBusStopId");
            return (Criteria) this;
        }

        public Criteria andDepartureTimeIsNull() {
            addCriterion("departure_time is null");
            return (Criteria) this;
        }

        public Criteria andDepartureTimeIsNotNull() {
            addCriterion("departure_time is not null");
            return (Criteria) this;
        }

        public Criteria andDepartureTimeEqualTo(Date value) {
            addCriterionForJDBCTime("departure_time =", value, "departureTime");
            return (Criteria) this;
        }

        public Criteria andDepartureTimeNotEqualTo(Date value) {
            addCriterionForJDBCTime("departure_time <>", value, "departureTime");
            return (Criteria) this;
        }

        public Criteria andDepartureTimeGreaterThan(Date value) {
            addCriterionForJDBCTime("departure_time >", value, "departureTime");
            return (Criteria) this;
        }

        public Criteria andDepartureTimeGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCTime("departure_time >=", value, "departureTime");
            return (Criteria) this;
        }

        public Criteria andDepartureTimeLessThan(Date value) {
            addCriterionForJDBCTime("departure_time <", value, "departureTime");
            return (Criteria) this;
        }

        public Criteria andDepartureTimeLessThanOrEqualTo(Date value) {
            addCriterionForJDBCTime("departure_time <=", value, "departureTime");
            return (Criteria) this;
        }

        public Criteria andDepartureTimeIn(List<Date> values) {
            addCriterionForJDBCTime("departure_time in", values, "departureTime");
            return (Criteria) this;
        }

        public Criteria andDepartureTimeNotIn(List<Date> values) {
            addCriterionForJDBCTime("departure_time not in", values, "departureTime");
            return (Criteria) this;
        }

        public Criteria andDepartureTimeBetween(Date value1, Date value2) {
            addCriterionForJDBCTime("departure_time between", value1, value2, "departureTime");
            return (Criteria) this;
        }

        public Criteria andDepartureTimeNotBetween(Date value1, Date value2) {
            addCriterionForJDBCTime("departure_time not between", value1, value2, "departureTime");
            return (Criteria) this;
        }

        public Criteria andArrivalTimeIsNull() {
            addCriterion("arrival_time is null");
            return (Criteria) this;
        }

        public Criteria andArrivalTimeIsNotNull() {
            addCriterion("arrival_time is not null");
            return (Criteria) this;
        }

        public Criteria andArrivalTimeEqualTo(Date value) {
            addCriterionForJDBCTime("arrival_time =", value, "arrivalTime");
            return (Criteria) this;
        }

        public Criteria andArrivalTimeNotEqualTo(Date value) {
            addCriterionForJDBCTime("arrival_time <>", value, "arrivalTime");
            return (Criteria) this;
        }

        public Criteria andArrivalTimeGreaterThan(Date value) {
            addCriterionForJDBCTime("arrival_time >", value, "arrivalTime");
            return (Criteria) this;
        }

        public Criteria andArrivalTimeGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCTime("arrival_time >=", value, "arrivalTime");
            return (Criteria) this;
        }

        public Criteria andArrivalTimeLessThan(Date value) {
            addCriterionForJDBCTime("arrival_time <", value, "arrivalTime");
            return (Criteria) this;
        }

        public Criteria andArrivalTimeLessThanOrEqualTo(Date value) {
            addCriterionForJDBCTime("arrival_time <=", value, "arrivalTime");
            return (Criteria) this;
        }

        public Criteria andArrivalTimeIn(List<Date> values) {
            addCriterionForJDBCTime("arrival_time in", values, "arrivalTime");
            return (Criteria) this;
        }

        public Criteria andArrivalTimeNotIn(List<Date> values) {
            addCriterionForJDBCTime("arrival_time not in", values, "arrivalTime");
            return (Criteria) this;
        }

        public Criteria andArrivalTimeBetween(Date value1, Date value2) {
            addCriterionForJDBCTime("arrival_time between", value1, value2, "arrivalTime");
            return (Criteria) this;
        }

        public Criteria andArrivalTimeNotBetween(Date value1, Date value2) {
            addCriterionForJDBCTime("arrival_time not between", value1, value2, "arrivalTime");
            return (Criteria) this;
        }

        public Criteria andPriceIsNull() {
            addCriterion("price is null");
            return (Criteria) this;
        }

        public Criteria andPriceIsNotNull() {
            addCriterion("price is not null");
            return (Criteria) this;
        }

        public Criteria andPriceEqualTo(Integer value) {
            addCriterion("price =", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceNotEqualTo(Integer value) {
            addCriterion("price <>", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceGreaterThan(Integer value) {
            addCriterion("price >", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceGreaterThanOrEqualTo(Integer value) {
            addCriterion("price >=", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceLessThan(Integer value) {
            addCriterion("price <", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceLessThanOrEqualTo(Integer value) {
            addCriterion("price <=", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceIn(List<Integer> values) {
            addCriterion("price in", values, "price");
            return (Criteria) this;
        }

        public Criteria andPriceNotIn(List<Integer> values) {
            addCriterion("price not in", values, "price");
            return (Criteria) this;
        }

        public Criteria andPriceBetween(Integer value1, Integer value2) {
            addCriterion("price between", value1, value2, "price");
            return (Criteria) this;
        }

        public Criteria andPriceNotBetween(Integer value1, Integer value2) {
            addCriterion("price not between", value1, value2, "price");
            return (Criteria) this;
        }

        public Criteria andBusIdIsNull() {
            addCriterion("bus_id is null");
            return (Criteria) this;
        }

        public Criteria andBusIdIsNotNull() {
            addCriterion("bus_id is not null");
            return (Criteria) this;
        }

        public Criteria andBusIdEqualTo(Integer value) {
            addCriterion("bus_id =", value, "busId");
            return (Criteria) this;
        }

        public Criteria andBusIdNotEqualTo(Integer value) {
            addCriterion("bus_id <>", value, "busId");
            return (Criteria) this;
        }

        public Criteria andBusIdGreaterThan(Integer value) {
            addCriterion("bus_id >", value, "busId");
            return (Criteria) this;
        }

        public Criteria andBusIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("bus_id >=", value, "busId");
            return (Criteria) this;
        }

        public Criteria andBusIdLessThan(Integer value) {
            addCriterion("bus_id <", value, "busId");
            return (Criteria) this;
        }

        public Criteria andBusIdLessThanOrEqualTo(Integer value) {
            addCriterion("bus_id <=", value, "busId");
            return (Criteria) this;
        }

        public Criteria andBusIdIn(List<Integer> values) {
            addCriterion("bus_id in", values, "busId");
            return (Criteria) this;
        }

        public Criteria andBusIdNotIn(List<Integer> values) {
            addCriterion("bus_id not in", values, "busId");
            return (Criteria) this;
        }

        public Criteria andBusIdBetween(Integer value1, Integer value2) {
            addCriterion("bus_id between", value1, value2, "busId");
            return (Criteria) this;
        }

        public Criteria andBusIdNotBetween(Integer value1, Integer value2) {
            addCriterion("bus_id not between", value1, value2, "busId");
            return (Criteria) this;
        }

        public Criteria andRunStartDateIsNull() {
            addCriterion("run_start_date is null");
            return (Criteria) this;
        }

        public Criteria andRunStartDateIsNotNull() {
            addCriterion("run_start_date is not null");
            return (Criteria) this;
        }

        public Criteria andRunStartDateEqualTo(Date value) {
            addCriterionForJDBCDate("run_start_date =", value, "runStartDate");
            return (Criteria) this;
        }

        public Criteria andRunStartDateNotEqualTo(Date value) {
            addCriterionForJDBCDate("run_start_date <>", value, "runStartDate");
            return (Criteria) this;
        }

        public Criteria andRunStartDateGreaterThan(Date value) {
            addCriterionForJDBCDate("run_start_date >", value, "runStartDate");
            return (Criteria) this;
        }

        public Criteria andRunStartDateGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("run_start_date >=", value, "runStartDate");
            return (Criteria) this;
        }

        public Criteria andRunStartDateLessThan(Date value) {
            addCriterionForJDBCDate("run_start_date <", value, "runStartDate");
            return (Criteria) this;
        }

        public Criteria andRunStartDateLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("run_start_date <=", value, "runStartDate");
            return (Criteria) this;
        }

        public Criteria andRunStartDateIn(List<Date> values) {
            addCriterionForJDBCDate("run_start_date in", values, "runStartDate");
            return (Criteria) this;
        }

        public Criteria andRunStartDateNotIn(List<Date> values) {
            addCriterionForJDBCDate("run_start_date not in", values, "runStartDate");
            return (Criteria) this;
        }

        public Criteria andRunStartDateBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("run_start_date between", value1, value2, "runStartDate");
            return (Criteria) this;
        }

        public Criteria andRunStartDateNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("run_start_date not between", value1, value2, "runStartDate");
            return (Criteria) this;
        }

        public Criteria andRunEndDateIsNull() {
            addCriterion("run_end_date is null");
            return (Criteria) this;
        }

        public Criteria andRunEndDateIsNotNull() {
            addCriterion("run_end_date is not null");
            return (Criteria) this;
        }

        public Criteria andRunEndDateEqualTo(Date value) {
            addCriterionForJDBCDate("run_end_date =", value, "runEndDate");
            return (Criteria) this;
        }

        public Criteria andRunEndDateNotEqualTo(Date value) {
            addCriterionForJDBCDate("run_end_date <>", value, "runEndDate");
            return (Criteria) this;
        }

        public Criteria andRunEndDateGreaterThan(Date value) {
            addCriterionForJDBCDate("run_end_date >", value, "runEndDate");
            return (Criteria) this;
        }

        public Criteria andRunEndDateGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("run_end_date >=", value, "runEndDate");
            return (Criteria) this;
        }

        public Criteria andRunEndDateLessThan(Date value) {
            addCriterionForJDBCDate("run_end_date <", value, "runEndDate");
            return (Criteria) this;
        }

        public Criteria andRunEndDateLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("run_end_date <=", value, "runEndDate");
            return (Criteria) this;
        }

        public Criteria andRunEndDateIn(List<Date> values) {
            addCriterionForJDBCDate("run_end_date in", values, "runEndDate");
            return (Criteria) this;
        }

        public Criteria andRunEndDateNotIn(List<Date> values) {
            addCriterionForJDBCDate("run_end_date not in", values, "runEndDate");
            return (Criteria) this;
        }

        public Criteria andRunEndDateBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("run_end_date between", value1, value2, "runEndDate");
            return (Criteria) this;
        }

        public Criteria andRunEndDateNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("run_end_date not between", value1, value2, "runEndDate");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table public.route
     *
     * @mbg.generated do_not_delete_during_merge Tue Jun 02 05:35:19 JST 2020
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table public.route
     *
     * @mbg.generated Tue Jun 02 05:35:19 JST 2020
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}