package vn.com.vti.bus.entity;

public class Seat {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.seat.seat_id
     *
     * @mbg.generated Fri Oct 28 23:10:12 JST 2022
     */
    private Integer seatId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.seat.bus_id
     *
     * @mbg.generated Fri Oct 28 23:10:12 JST 2022
     */
    private Integer busId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.seat.reserve_id
     *
     * @mbg.generated Fri Oct 28 23:10:12 JST 2022
     */
    private Integer reserveId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.seat.seat_number
     *
     * @mbg.generated Fri Oct 28 23:10:12 JST 2022
     */
    private Integer seatNumber;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.seat.seat_id
     *
     * @return the value of public.seat.seat_id
     *
     * @mbg.generated Fri Oct 28 23:10:12 JST 2022
     */
    public Integer getSeatId() {
        return seatId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.seat.seat_id
     *
     * @param seatId the value for public.seat.seat_id
     *
     * @mbg.generated Fri Oct 28 23:10:12 JST 2022
     */
    public void setSeatId(Integer seatId) {
        this.seatId = seatId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.seat.bus_id
     *
     * @return the value of public.seat.bus_id
     *
     * @mbg.generated Fri Oct 28 23:10:12 JST 2022
     */
    public Integer getBusId() {
        return busId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.seat.bus_id
     *
     * @param busId the value for public.seat.bus_id
     *
     * @mbg.generated Fri Oct 28 23:10:12 JST 2022
     */
    public void setBusId(Integer busId) {
        this.busId = busId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.seat.reserve_id
     *
     * @return the value of public.seat.reserve_id
     *
     * @mbg.generated Fri Oct 28 23:10:12 JST 2022
     */
    public Integer getReserveId() {
        return reserveId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.seat.reserve_id
     *
     * @param reserveId the value for public.seat.reserve_id
     *
     * @mbg.generated Fri Oct 28 23:10:12 JST 2022
     */
    public void setReserveId(Integer reserveId) {
        this.reserveId = reserveId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.seat.seat_number
     *
     * @return the value of public.seat.seat_number
     *
     * @mbg.generated Fri Oct 28 23:10:12 JST 2022
     */
    public Integer getSeatNumber() {
        return seatNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.seat.seat_number
     *
     * @param seatNumber the value for public.seat.seat_number
     *
     * @mbg.generated Fri Oct 28 23:10:12 JST 2022
     */
    public void setSeatNumber(Integer seatNumber) {
        this.seatNumber = seatNumber;
    }
}